language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - chmod +x gradlew
notifications:
  slack:
    secure: YgypqHTuYeC438N3lisGz0Mf/juwQZEoWEiUNxELGobi7JwvvZshuIl3OzSJrU8nqO1W3f76ZdeQwcEPbqVEm/ZlkfI4+ycc9nNp/cDQtM4YC+7XcjcP5Ot1rMiuxF+8I/FSlL7PQoB2vn2sKwiKQ/NJrZtXExEFMppyiowIs3N8R5DyT6Mj9ReqiImQaXrNlMvxM2Tr4WEAZY2yDuUtxa6oyBr7d2meN+9kS93Qap8GtHzryKtVcOCoiAptf7EwscqymajQr5b8PdTupXOX3b826u5Do9Yg+IsesfChvP59iHD56Jz/NMRKAL/5bWMXJszWFWQGcqk7LLJtv9rmCCSeUXPHJk07CpEK6+dUKhWlpU/irzW59KTJ2Cthyr/arQKbPbY/TNkYEIjVXVqnxWr8peeLnxG75U9eHX7hxJWslvgUuIdn1k6EYbVTA6RA8y2tZ4WSfyn4R0ka1UwnadHMhsPscj/vnjlfhoyUiQFmoTjEML9JacggjgEmv84La1LRoCvZyR1ugHxs38jGOJySlmNB3m5OHGo6NsAFSglKwN/ooM6oG0lwG4yIH88SFRBCzi/Pdh7wqli0+Im0oyX7FICs7x6Oib1QN/3JFijYQsnTLUWDXFKlTWVShZC90pp85GIGZ6vFaDXWwLWoSG3feTryQjbUu5xQsNNE/38=
