language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - chmod +x gradlew
notifications:
  slack:
    secure: U9IdRoFWhL17VSRBELXPSs9gsbALa/cMK5fUiIICmipr5JexG6igEj3aG+uWS2XK5x6tjcokbwn0Khw+lcKuWL5H1gKGQmLDsV6PCo0wkVqNB5PZ0KGWqIfpEZxdec0zWnU42fIvxJ1aveShLIAI4IoVha9KS4k0OB55f8cV0mc5zGrmNLPYyL/gaJzKLh61ZfwNB3/1PocsM5qvxM39J7G/4201SVWU/Y+YOWFR3qUIYw7vwKFFDV/5gsKT62FAJrL+FO7A7juTTDGDRiweHxDoy3k1+uUwok7gOiSWr9MVDvwdReg9xr8PWHesQOc8D+24VN5cCzSYTLhC0b8oni+VhnnkZleQyzYx6ZzwX4RXGIeNz0XXxCMVb120ul5IfhccFXM+5THKMndteIyZXH+kIEn+a3VWb+2KhJ2RIkkUFVX4JLi+ZxJ23p7WVX3lLXZ+EK92GBbNjCu+qRt+7UAZ8n/S/JPVCwgE4Wv7ZdbGc36lPqvrAe7UUjrVqIDyrwiMajx2ZK8AuAtSxZPzDWrL3x2quk+e4v41U+y329eKbg0zMdBxFt74nqnljSOEPZw8u4JK8mfAj5kYoTM8N561vajXHdVfVqP0Z7tth4BfDYgbvwT47SrLUYIDHfR15bUQneJWiA2nN77LxaECbpvV1YkoUPknxm46pHPq+uE=
